backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://fchpr.netlify.com
display_url: https://fchpr.netlify.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "title", label: "Title" }
      - { name: "body", label: "Body", widget: "markdown" }